apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitlab-bot
  name: gitlab-bot
  namespace: gitlab-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-bot
  template:
    metadata:
      labels:
        app: gitlab-bot
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: gitlab-bot-env
        image: gitlab-bot # TODO change with your needs
        imagePullPolicy: Always
        name: gitlab-bot
        volumeMounts:
        - mountPath: /config/
          name: gitlab-bot-config
          readOnly: true # TODO You can delete this and use a Persistent Volume Claim to map a writeable volume for configuration by Telegram
      volumes:
      - configMap:
          defaultMode: 420
          name: gitlab-bot-config
        name: gitlab-bot-config

