apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: gitlab-bot
  namespace: gitlab-bot
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: docker-registry.default.svc:5000/gitlab-bot/gitlab-bot
  tags:

